export {default as AppLogo} from "./AppLogo.svg"
export {default as Eyes} from "./Eyes.svg"
export {default as ShareIcon} from "./ShareIcon.svg"
export {default as Prescription} from "./prescription.svg"
export {default as Registration} from "./registration.svg"
export {default as BackArrow} from "./backArrow.svg"
export {default as SmallAppLogo} from "./smallAppLogo.svg"
export {default as Filter} from "./filter.svg"