export const COLORS={
SECONDARY_GRAY:'#5C5C5C',
PRIMARY_BLACK:'#000000',

APPBACK_GROUND:'#EFF8FC',
//inputBackGround
PRIMARY_WHITE:'#FFFFFF',
SECONDARY_WHITE:'#ECEDF0',

PRIMARY_BLUE:'#4490DF',
SECONDARY_BLUE:'#254C93',
PRIMARY_RED:'#F00'
}

export const FONTS={
    MONTESERRAT_SEMIBOLD:"Montserrat-SemiBold",
    MONTESRRAT_MEDIUM:"Montserrat-Medium"
}